
-- created database
CREATE DATABASE todolist;

-- createdb todolist;
CREATE TABLE account (
    username VARCHAR(50) PRIMARY KEY NOT NULL,
    password VARCHAR(100) NOT NULL, -- most hashing algorithms such as bcrypt produce a hash of around 60 characters.
    email VARCHAR(100) NOT NULL UNIQUE CHECK (email ~*'^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
    phonenumber VARCHAR(15) UNIQUE CHECK (phonenumber ~'^[0-9]{10,13}$')2,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    deleted_at TIMESTAMP
)

CREATE INDEX idx_username_email ON account(username,email,phonenumber);

CREATE TABLE group_note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    user_account VARCHAR(255) REFERENCES account(username) ON DELETE CASCADE NOT NULL,
    title VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    deleted_at TIMESTAMP
)

CREATE INDEX idx_group_id ON group_note(id);

CREATE TABLE note (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    group_note_id BIGINT REFERENCES group_note(id) ON DELETE CASCADE,
    title VARCHAR(100),
    text_content TEXT,
    checked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    Updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    deleted_at TIMESTAMP
)


